##### P0 基础准备
1. 一些函数的用法和知识
2. 神经网络的一些基本知识
3. Pytorch的基本用法

##### Function

In [ ]:
# 1. join
lst = ["a","b","c"]
res = "-".join(lst)
print(res)  # a-b-c

a-b-c


In [2]:
# 2. 字典推导
chars = ['a','b','c']
stoi = {s:i+1 for i,s in enumerate(chars)}
print(stoi)
# 结果：{'a':1, 'b':2, 'c':3}

{'a': 1, 'b': 2, 'c': 3}


In [ ]:
# 3. list
w = "hello"
print(list(w))
# ['h','e','l','l','o']
t = (1,2,3)
list(t)  # [1,2,3]

['h', 'e', 'l', 'l', 'o']


[1, 2, 3]

In [ ]:
# 4. zip
a = [1,2,3]
b = [4,5,6]
for x,y in zip(a,b):
    print(x,y)
# 1 4
# 2 5
# 3 6

1 4
2 5
3 6


In [ ]:
# 5. shuffle
import random
words = [1,2,3,4]
random.shuffle(words)
print(words) # 顺序被打乱

[4, 1, 3, 2]


##### Pytorch

In [ ]:
# 创建tensor1
import torch

# 1. 普通张量
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([[1,2],[3,4]])

# 指定数据类型
t3 = torch.tensor([1.1,2.2], dtype=torch.float32)
# 全0 全1
torch.zeros(2,3)      # 2行3列全0
torch.ones(3,4)       # 3行4列全1

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
# 创建tensor2
import torch

# 1. 创建随机生成器并固定种子
g = torch.Generator().manual_seed(42)

# 2. 用这个生成器创建正态分布随机张量
# 形状：3行4列
w = torch.randn((3, 4), generator=g)

print(w)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])


In [2]:
import torch

# 构造二维张量 形状[2,3]
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
print("原张量形状:", x.shape)
print(x)
print("-" * 30)

# 1. dim=0 纵向求和
s0 = x.sum(dim=0)
s0_keep = x.sum(dim=0, keepdim=True)
print("dim=0 不带keepdim：", s0.shape, s0)
print("dim=0 带keepdim：", s0_keep.shape, s0_keep)
print("-" * 30)

# 2. dim=1 横向求和
s1 = x.sum(dim=1)
s1_keep = x.sum(dim=1, keepdim=True)
print("dim=1 不带keepdim：", s1.shape, s1)
print("dim=1 带keepdim：", s1_keep.shape, s1_keep)

原张量形状: torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
------------------------------
dim=0 不带keepdim： torch.Size([3]) tensor([5, 7, 9])
dim=0 带keepdim： torch.Size([1, 3]) tensor([[5, 7, 9]])
------------------------------
dim=1 不带keepdim： torch.Size([2]) tensor([ 6, 15])
dim=1 带keepdim： torch.Size([2, 1]) tensor([[ 6],
        [15]])
